import { z } from "zod";
import { extractJsonObject } from "../utils/text.js";
import { ReasoningAssessmentSchema, ReasoningStateSchema, ReasoningVerdictSchema, type ReasoningAssessmentInput, type ReasoningController, type ReasoningFinalInput, type ReasoningInitContext, type ReasoningResponse } from "./reasoning.js";
export interface OpenAICompatibleReasoningOptions { baseUrl: string; apiKey?: string; model?: string; provider?: string; timeoutMs?: number; fetch?: typeof globalThis.fetch }
const ResponseSchema = z.object({ choices: z.array(z.object({ message: z.object({ content: z.string() }).passthrough() }).passthrough()).min(1), usage: z.object({ total_tokens: z.number().optional() }).passthrough().optional() }).passthrough();
export class OpenAICompatibleReasoningController implements ReasoningController {
  readonly provider: string; readonly model: string; private fetcher: typeof fetch; private retryInstruction?: string;
  constructor(private readonly options: OpenAICompatibleReasoningOptions) { this.provider = options.provider ?? "spark"; this.model = options.model ?? "spark-x2.5-1.7b"; this.fetcher = options.fetch ?? fetch; }
  initialize(input: ReasoningInitContext) { return this.call(ReasoningStateSchema, { task: "initialize", goal: input.goal, caller_success_criteria: input.successCriteria }, input.signal); }
  assess(input: ReasoningAssessmentInput) { return this.call(ReasoningAssessmentSchema, { task: "assess", state: input.state, trigger: input.trigger, page: { url: input.observation.url, title: input.observation.title, text: input.observation.visibleText?.slice(0, 3000), controls: input.observation.elements.slice(0, 30).map(x => ({ role: x.role, name: x.name, enabled: x.enabled })) }, recent_actions: input.recentActions.slice(-5), laya_decision: input.layaDecision, progress: input.progress }, input.signal); }
  finalize(input: ReasoningFinalInput) { return this.call(ReasoningVerdictSchema, { task: "finalize", state: input.state, termination: input.termination, assessment: input.assessment }, input.signal); }
  setRetryInstruction(instruction: string) { this.retryInstruction = instruction; }
  private async call<T>(schema: z.ZodType<T>, packet: unknown, signal: AbortSignal): Promise<ReasoningResponse<T>> { const retryInstruction = this.retryInstruction; this.retryInstruction = undefined; const started = Date.now(); const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), this.options.timeoutMs ?? 30_000); const abort = () => controller.abort(); signal.addEventListener("abort", abort, { once: true }); try { const endpoint = new URL("chat/completions", this.options.baseUrl.endsWith("/") ? this.options.baseUrl : `${this.options.baseUrl}/`); const apiKey = this.options.apiKey?.trim(); const response = await this.fetcher(endpoint, { method: "POST", headers: { "content-type": "application/json", ...(apiKey ? { authorization: `Bearer ${apiKey}` } : {}) }, body: JSON.stringify({ model: this.model, temperature: 0, messages: [{ role: "system", content: "You are JourneyTest System-2. Return only one JSON object matching the supplied schema. Never return executable browser or shell instructions." }, { role: "user", content: `${JSON.stringify(packet)}\n${retryInstruction ? `Retry instruction: ${retryInstruction}\n` : ""}Schema: ${JSON.stringify(z.toJSONSchema(schema))}` }] }), signal: controller.signal }); if (!response.ok) throw new Error(`${this.provider} HTTP ${response.status}`); const body = ResponseSchema.parse(await response.json()); return { value: schema.parse(extractJsonObject(body.choices[0].message.content)), metadata: { provider: this.provider, model: this.model, latencyMs: Date.now() - started, tokens: body.usage?.total_tokens } }; } finally { clearTimeout(timer); signal.removeEventListener("abort", abort); } }
}
