import { describe, expect, it } from "vitest";
import { DefaultCognitionRouter, ReasoningRoutingError, RetryingReasoningController } from "../src/journey/cognition.js";
import { loadRuntimeCognitionConfig } from "../src/app/cognitionConfig.js";
import type { AgentDecision, JourneyAgent, Observation } from "../src/journey/types.js";
import type { ReasoningAssessment, ReasoningController, ReasoningResponse, ReasoningState, ReasoningVerdict } from "../src/journey/reasoning.js";
const signal = new AbortController().signal;
const observation: Observation = { url: "https://example.test", title: "Home", visibleText: "Home", elements: [{ ref: "pricing", role: "link", name: "Pricing", enabled: true, operations: ["CLICK"] }] };
const context = { journeyId: "j", goal: "Open pricing", metadata: {}, signal };
function agent(decision: AgentDecision | Error): JourneyAgent { return { name: "test", backend: "test", decide: async () => { if (decision instanceof Error) throw decision; return decision; } }; }
function response<T>(value: T, provider = "test"): ReasoningResponse<T> { return { value, metadata: { provider, model: "test", latencyMs: 1 } }; }
class Reasoner implements ReasoningController { provider = "test"; model = "test"; calls = 0; constructor(readonly assessment: ReasoningAssessment | Error) {} async initialize(): Promise<ReasoningResponse<ReasoningState>> { return response({ goal: "Open pricing", success_criteria: [] }); } async assess(): Promise<ReasoningResponse<ReasoningAssessment>> { this.calls++; if (this.assessment instanceof Error) throw this.assessment; return response(this.assessment); } async finalize(): Promise<ReasoningResponse<ReasoningVerdict>> { return response({ goal_satisfied: false, blocked: false, confidence: 1, criteria: [], reason_code: "final" }); } }
function config(profile: string, extra: Record<string,string> = {}) { return loadRuntimeCognitionConfig({ env: { COGNITION_PROFILE: profile, REASONING_PROVIDER: "openai", REASONING_MODEL: "gpt-4o-mini", OPENAI_API_KEY: "test-openai-key", CLOUD_REASONING_ENABLED: "true", ...(profile.includes("spark") ? { SPARK_REASONING_ENABLED: "true", SPARK_OPENAI_BASE_URL: "http://spark.test/v1" } : {}), ...(profile.startsWith("dual") ? { LAYA_HOSTED_ENABLED: "true", LAYA_HOSTED_BASE_URL: "https://hosted.test", LAYA_HOSTED_FALLBACK_ENABLED: "true" } : {}), ...extra } }); }
const done: ReasoningAssessment = { decision: "DONE", goal_satisfied: true, blocked: false, progress: "complete", reason_code: "done", confidence: 1 };
const cont: ReasoningAssessment = { decision: "CONTINUE", goal_satisfied: false, blocked: false, progress: "partial", reason_code: "continue", confidence: 1 };
const assessInput = { state: { goal: "Open pricing", success_criteria: [] }, trigger: "termination_candidate" as const, observation, recentActions: [], progress: { urlChanged: false, repeatedActionCount: 1, noProgressSteps: 0 }, signal };

describe("CognitionRouter profiles", () => {
  for (const profile of ["local-cloud", "local-spark-cloud", "dual-laya-cloud", "dual-laya-spark-cloud"] as const) it(`${profile} keeps local Laya primary`, async () => { const cloud = new Reasoner(cont); const spark = new Reasoner(cont); const router = new DefaultCognitionRouter({ config: config(profile), localLaya: agent({ operation: "CLICK", elementIndex: 0, confidence: .9 }), hostedLaya: agent({ operation: "WAIT", confidence: .8 }), spark, cloud }); const routed = await router.chooseAction({ observation, state: { step: 1 }, context }); expect(routed.evidence.system1Backend).toBe("local_laya"); expect(routed.evidence.layaComparison).toBeUndefined(); await router.assessJourney(assessInput); expect(profile.includes("spark") ? spark.calls : cloud.calls).toBe(1); });
  it("falls back to hosted Laya after a local transport failure", async () => { const router = new DefaultCognitionRouter({ config: config("dual-laya-cloud"), localLaya: agent(new Error("timeout")), hostedLaya: agent({ operation: "WAIT", confidence: .8 }), cloud: new Reasoner(cont) }); expect((await router.chooseAction({ observation, state: { step: 1 }, context })).evidence.system1Backend).toBe("hosted_laya"); });
  it("records agreement and disagreement only on conditional verification", async () => { for (const hosted of [{ operation: "CLICK", elementIndex: 0, confidence: .8 }, { operation: "WAIT", confidence: .8 }] as AgentDecision[]) { const router = new DefaultCognitionRouter({ config: config("dual-laya-cloud"), localLaya: agent({ operation: "CLICK", elementIndex: 0, confidence: .9 }), hostedLaya: agent(hosted), cloud: new Reasoner(cont) }); expect((await router.chooseAction({ observation, state: { step: 1 }, context, verify: true })).evidence.layaComparison?.agreement).toBe(hosted.operation === "CLICK"); } });
  it("uses Vision only when text/DOM evidence is inadequate", async () => { const router = new DefaultCognitionRouter({ config: config("local-cloud", { LAYA_VISION_ENABLED: "true", LAYA_VISION_BASE_URL: "https://vision.test" }), localLaya: agent({ operation: "WAIT", confidence: .5 }), vision: agent({ operation: "CLICK", elementIndex: 0, confidence: .9 }), cloud: new Reasoner(cont) }); const empty = { ...observation, visibleText: "", elements: [] }; expect((await router.chooseAction({ observation: empty, state: { step: 1 }, context })).evidence.visionUsed).toBe(true); });
  it("accepts valid Spark and structurally escalates ambiguous terminal Spark output", async () => { const spark = new Reasoner(cont); const cloud = new Reasoner(done); const router = new DefaultCognitionRouter({ config: config("local-spark-cloud"), localLaya: agent({ operation: "WAIT", confidence: 1 }), spark, cloud }); expect((await router.assessJourney(assessInput)).value.decision).toBe("CONTINUE"); spark.assessment = done; expect((await router.assessJourney(assessInput)).value.decision).toBe("DONE"); expect(cloud.calls).toBe(1); });
  it("escalates invalid Spark output to cloud", async () => { const router = new DefaultCognitionRouter({ config: config("local-spark-cloud"), localLaya: agent({ operation: "WAIT", confidence: 1 }), spark: new Reasoner(new Error("schema invalid")), cloud: new Reasoner(cont) }); expect((await router.assessJourney(assessInput)).metadata.escalationReason).toContain("structured_output"); });
});

describe("bounded reasoning retries", () => {
  it("retries transport and structured failures then succeeds", async () => { let calls = 0; const inner = new Reasoner(cont); inner.assess = async () => { calls++; if (calls === 1) throw new Error("timeout"); if (calls === 2) throw new Error("schema invalid"); return response(cont); }; const retry = new RetryingReasoningController(inner, { backend: "cloud", maxAttempts: 3, timeoutMs: 100, retryBaseMs: 0, jitter: () => 0 }); const result = await retry.assess(assessInput); expect(calls).toBe(3); expect(result.metadata.attempts).toBe(3); expect(retry.attempts.map(x => x.failureClass)).toEqual(["transport", "structured_output", undefined]); });
  it("uses a verification retry for a valid but explicitly ambiguous response", async () => { let calls = 0; const ambiguous = { ...cont, reason_code: "insufficient_evidence" }; const inner = new Reasoner(ambiguous); inner.assess = async () => response(++calls === 1 ? ambiguous : cont); const retry = new RetryingReasoningController(inner, { backend: "cloud", maxAttempts: 2, timeoutMs: 100, retryBaseMs: 0, jitter: () => 0 }); const result = await retry.assess(assessInput); expect(calls).toBe(2); expect(result.metadata.retryEvents?.[0]).toMatchObject({ failureClass: "ambiguous", success: false }); });
  it("returns structured exhaustion without leaking the underlying message", async () => { const retry = new RetryingReasoningController(new Reasoner(new Error("timeout secret-key")), { backend: "cloud", maxAttempts: 2, timeoutMs: 100, retryBaseMs: 0, jitter: () => 0 }); await expect(retry.assess(assessInput)).rejects.toMatchObject<Partial<ReasoningRoutingError>>({ category: "transport", attempts: expect.arrayContaining([expect.objectContaining({ success: false })]) }); await expect(retry.assess(assessInput)).rejects.not.toThrow("secret-key"); });
});
